### ISSUE TITLE
Subclasses and initialisation?

### ISSUE THREAD

**Issue by jdickey** [mushishi78/attire#1]
Given

``` ruby
class Foo
  def initialize(foo, bar = 25)
    # ...
  end
  # ...
end

class Bar < Foo
  def initialize(foo, bat, bar = 50)
    super foo, bar
    @bat = twiddle_bat(bat)
  end
  # ...
end
```

converting `Foo` is straightforward as

```
class Foo
  attr_init :foo, bar: 25
  # ...
end
```

but what to do with `Bar`?

**Comment by mushishi78** [comment]
Your question isn't very specific, but for your example you can do this:

``` ruby
class Bar < Foo
  attr_init :foo, :bat, bar: 50 do
    @bat = twiddle_bat(bat)
  end
  #...
end
```

However, for more complex examples where you want to use `super` you may have some trouble as you can't call `super` from a block. So you'd probably have to `alias_method` on `initialize` or something, which might be more hacky than it's worth, depending on the context.

Hope that helps :)

**Comment by jdickey** [comment]
Thanks. That's about what I figured; you understood my meaning clearly. It's Very Useful code; there's just a few clusters of classes in my existing project I've been meaning to rethink, eventually. "Eventually" just became a lot closer. :sweat_smile:
