### ISSUE TITLE
Keyword parameters to `#initialize`?

### ISSUE THREAD

**Issue by jdickey** [mushishi78/attire#2]
I have an existing class' `#initialize` method that looks like this:

``` ruby
      def initialize(slug:, current_user:, repository:)
        @slug = slug
        @current_user = current_user
        @repository = repository
        self
      end
```

Pretty obvious candidate for `attr_init`, yes? Except for one thing: you'll notice that this method has Ruby 2.0 keyword parameters, and there's a _significant_ amount of other code in the app that depends on that. How difficult would it be to add (optional) support for keyword parameters to `attr_init`?

**Comment by mushishi78** [comment]
Oh I see. It's not Ruby 2.0 keywords per se, but Ruby 2.1's required keywords, which I happen to never have seen before. A quick fix would look like this:

``` ruby
attr_init slug: nil, current_user: nil, repository: nil do
  fail ArgumentError unless slug && curent_user && repository
end
```

As for support, the problem is that that syntax is only allowed in a method definition, I couldn't make it work like this:

``` ruby
attr_init slug:, current_user:, repository:
```

Because ruby wouldn't allow that, so I'd have to make it work like this:

``` ruby
attr_init :'slug:' => nil, :'current_user:' => nil, :'repository:' => nil
```

And I think that would be really confusing...

I think the better alternative would be to create a new implementation for Ruby >= 2.0 where instead of using the `attr_init` class method, you would include `Attire::Initializer` module that would listen for an initialize method to be defined. So you'd end up with:

``` ruby
class MyClass
  include Attire::Initializer

  def initialize(slug:, current_user:, repository:)
  end
end
```

This way Attire no longer would have to deal with argument checking and it could support any new parameter syntax. It also wouldn't pollute the Module class with methods.

I'll have a quick go of implementing this now, but I might have to put it off if it takes awhile.

**Comment by mushishi78** [comment]
Alright, if you try updating to the new version and then you should be able to write:

``` ruby
require 'attire'

class MyClass
  extend Attire::Initializer

  def initialize(slug:, current_user:, repository:)
  end
end
```

Note that it's `extend`, not `include` as I originally wrote.

**Comment by jdickey** [comment]
@mushishi78  That looks perfectly reasonable, and we still get some benefit from Attire. I bet that won't even make [Contracts](https://github.com/egonSchiele/contracts.ruby) blink, which is the other bit of magic cleanup sauce I've been applying to my project over the last couple of days. Thanks!

**Edited:** No, it didn't solve the [conflict with Contracts](https://github.com/jdickey/new_poc/pull/272#issuecomment-99721854), but I'd see you arguing that "that's outside Attire's scope" as a perfectly legitimate response. I still expect to be using Attire from time to time; just not as pervasively as I'd initially hoped. Thanks again.

**Comment by mushishi78** [comment]
Well you piqued my interest so I tested it and stumbled upon the fact that it works with contracts 0.7. So if you just specify that version number in your Gemfile you should be fine. I don't know what they changed in version 0.8, but you can take out an issue with them if you like. What seems to be happening is it's applying the contract for the `initialize` method on the getters for some reason.

Note, you need to keep the `include Contracts` before `extend Attire::Initializer`, that's probably my fault but I'll fix that as when it becomes a problem.

Also, with contracts on `initialize` I image you don't need to return self, so this would probably be fine:

``` ruby
Contract INIT_CONTRACT_INPUTS => Any
def initialize(target_slug:, current_user:, repository:)
end
```

**Comment by jdickey** [comment]
@mushishi78 Wow; thanks for the effort and follow-up. I'll take another look at the conflict I was having, keeping that ordering you recommended in mind. If this is a new bug in their 0.8, I'd love to help nail it down. I think that's going to be another very-heavily-relied-upon component (along with Attire, hopefully).

As far as the `#initialize`-returning-`self` bit, I admit being infected by a _lot_ of [Jim Gay](https://www.youtube.com/watch?v=kXcrClJcfm8)'s (aka @saturnflyer) philosophy, as well as [Joel Spolsky](http://www.joelonsoftware.com/articles/LeakyAbstractions.html).

**Comment by mushishi78** [comment]
I took another look at it and rearranged the ordering of some code. So if you update to the newest version again, it should now work with Contracts >= 0.8.

**Comment by jdickey** [comment]
[Got it working](https://github.com/jdickey/new_poc/pull/272#issuecomment-100802299), thanks a lot!

Of course, considering the number of moving parts in the system, keeping _this_ part from going **boom** any more of course made something _else_ go **splat**. One of these days I might even get around to writing a PR for the complaining RuboCop cop so that it treats `#initialize` as a special case in classes extended by `Attire::Initializer`.

Thanks again; go ahead and close this issue as far as I'm concerned. :clap:
